//
// Created by nmWiN on 08.05.2022.
//

#ifndef ESP32_CONTROLLER_INCLUDE_DEFINITIONS_H_
#define ESP32_CONTROLLER_INCLUDE_DEFINITIONS_H_

#define BOARD_DATA_PIN 22
#define BOARD_WIFI_HOSTNAME					"magic_table"
#define BOARD_UI_HTTP_PORT					80
#define BOARD_UI_DEFAULT_FILENAME			"index.html"
#define BOARD_UI_WEB_SOCKET_URI				"/ws"

#define DEFAULT_WIFI_PARAMS_SSID 			"Viba.Net"
#define DEFAULT_WIFI_PARAMS_PASSWORD 		"c-GZVVl9tSYTqK$ggiuPibY3bsz!u1wtUeWXeLm!L8LtslYVgJs5XKWM8Ezl"

#define DEFAULT_ADMIN_PARAMS_USERNAME 		"admin"
#define DEFAULT_ADMIN_PARAMS_PASSWORD 		"admin"

#define DEFAULT_POWER_PARAMS_VOLTS          5
#define DEFAULT_POWER_PARAMS_MILLI_AMPS     8000
#define DEFAULT_POWER_PARAMS_MILLI_WATTS	DEFAULT_POWER_PARAMS_VOLTS * DEFAULT_POWER_PARAMS_MILLI_AMPS

#define DEFAULT_LEDS_PARAMS_COUNT 			300

#endif //ESP32_CONTROLLER_INCLUDE_DEFINITIONS_H_
